Map<String, String> enUS = {
  //'hi_IN': {'hello': 'नमस्ते'},
  "login": "Login",
  "email_id": "Email Id",
  "password": "Password",
  "forgot": "Forgot?",
  "create_account": "Create Account",
  "or_continue_with": "Or continue with",
  "by_continue": "By continue you agree that you have read and\naccept our",
  "t&c": "Term & Conditions",
  "and": " and ",
  "privacy_policy": "Privacy Policy",
  "obd1Title": "Search\nBest Food",
  "obdDes": "Ready to order from top home made food?",
  "obd2Title": "Make\nOrder Now",
  "obd3Title": "Fast\nDelivery",
  "check_your_email": "Check your email",
  "email_sent_des":
      "To confirm your email address, please tap the button in the email we sent to ",
  "mobile_sent_dis": "Enter 4-digit Code. We have sent to at ",
  "continue": "continue",
  "resend_link": "Resend Link",
  "manually_enter_otp": "Manually Enter OTP",
  "didn't_receive": "Didn’t receive the code?   ",
  "resend_otp": "Resend OTP",
  "sign_up": "Sign Up",
  "username": "User Name",
  "confirm_password": "Confirm Password",
  "already_have": "Already have an account?  ",
  "phone_number": "Phone Number",
  "otp_verification": "Otp Verification",
  "search_location": "Search Location",
  "search_for_your": "Search for your location...",
  "recent_location": "Recent Locations",
  //dashBoard
  "home": "Home",
  "search": "Search",
  "delivery": "Delivery",
  "order": "Order",
  //home
  "top_categories": "Top Categories",
  "show_all": "Show all",
  "off": "OFF",
  "review": "Review",
  "km": "kilometer(KM)",
  "read_less": " Read Less",
  "read_more": "Read More...",
  "availability": "Availability",
  "other_recipe": "Heny another recipe",
  "add_to_cart": "Add to Cart",
  "likes": "Likes",
  "reply": "Reply",
  "delete": "Delete",
  "edit": "Edit",
  //search
  "recipe_name_or_dish": "Recipe Name Or Dish...",
  "recent_search": "Recent Search",
  "reset_filter": "Reset Filter",
  "apply_filter": "Apply Filter",
  // checkout
  "order_details": "Order Details",
  "item_total": "Item Total",
  "delivery_fees": "Delivery Fee for ",
  "taxes_and_charges": "Texes and Charge",
  "coupon_saving": "Coupon Saving",
  "order_total": "Order Total",
  "order_to": "Order To ",
  "email_address": "Email Address",
  "proceed_to_pay": "proceed to pay",
  "view_price_detail": "View Price Detail",
  //profile
  "profile": "Profile",
  "mange_address": "Manage Address",
  "cook_profile": "Cook Profile",
  "favourites": "Favourites",
  "offers": "Offers",
  "payment_methods": "Payment Method",
  "manage_your_profile": "Manage Your Profile",
  "edit_your_location": "Manage Your Location",
  "register_as_cook": "Register As A Cook",
  "your_favourites_recipe": "Your Favourite Recipe",
  "new_available_offers": "New Available Offers",
  "change_and_add": "Change And Add Payment Method",
  "your_past_order": "Your Past Order",
  "logout": "Log Out",
  //edit profile
  "first_name": "First Name",
  "last_name": "Last Name",
  "reset": "Reset",
  "save": "Save",
  //add recipe
  "recipe_add_des": "Add Your\nDelicious Recipes",
  "register_here": "Register Here",
  "cancel": "Cancel",
  //register recipe
  "register": "Register",
  "save_next": "Save & Next",
  "house_flat": "house / Flat Block No.",
  "passcode": "Passcode",
  "state": "State",
  "valid_only": "Valid Only Last 5 Years Of Address",
  "pan_number": "Pancard Number",
  "aadhar_card_number": "Aadhar Card Number",
  //add recipe details
  "add_recipe_details": "Add Recipe Details",
  "upload_recipe_photo": "Upload Recipe Photo",
  "recipe_name": "Recipe Name",
  "recipe_des": "Recipe Description",
  "amount": "Amount",
  "quantity": "Quantity",
  "veg": "Veg",
  "non_veg": "Non-Veg",
  "food_category": "Food Category",
  "add_your_amount": "Add Your Amount",
  "weekly": "Weekly",
  "monthly": "Monthly",
  "submit": "Submit",
  //register page
  "t_c_apply": "Terms and condition apply",
  "edit_details": "Edit Details",

  //favourite
  "today": "Today",
  "yesterday": "Yesterday",
  "last_week": "Last Week",

  "order_history": "Order History",

  //textfield validation
  "field_required": "Field required",
};
